version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME=stock_db
      - DB_USER=postgres
      - DB_PASSWORD=P@ssw0rd
      - DB_HOST=db  # 指向 PostgreSQL 服務名稱
      - DB_PORT=5432
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_DB=stock_db
    ports:
      - "5432:5432"  # 映射到主機的 5432 端口
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
