services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  milvus:
    image: milvusdb/milvus:2.5-20250301-3f76e1c6-gpu-amd64
    ports:
      - "19530:19530"
    volumes:
      - milvus_data:/var/lib/milvus

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}
    ports:
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  elasticsearch:
    image: elasticsearch:8.17.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  mongo_data:
  milvus_data:
  neo4j_data:
  es_data:
  redis_data: