version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_NAME='stock_db'
      - DB_USER='postgres'
      - DB_PASSWORD='P@ssw0rd'
      - DB_HOST='localhost'
      - DB_PORT='5432'
